### PR TITLE
Initial project setup

### PR DESCRIPTION
**Pull request by peritus**
This rather huge pull request is the foundation of what is to start tomorrow, including

* travisci for continous integration
  * fast caching
  * testing against postgres 9.4 and python 3.3/3.4
* removed printf debugging
* proper dependencies
* a test
* a makefile to abstract away all the utility comfort you want in a dev env
* flake8 check and autopep8 command to fix it (also enforced by travis)
* setup instructions in a readme
* a real python module (called `gather2_core`)
* configuration that is both composable and overridable (powered by django-configurations)
* .. and much more

### CODE REVIEW

**Comment by peritus** [comment]
I can also clean up the commits a bit, if wanted (used the branch for travis debugging, so ..).

**Comment by readevalprint** [comment]
So how do you specify the database settings for dev?
I don't the the whole rename is necessary because this is the combined repo of the 3 components (collect, core, dashboard) and none of them should be sharing code or importing each other. 
But all in all +1

**Comment by peritus** [comment]
Like this:

```
DATABASE_URL=postgres://myuser@example.com/mydb bin/invoke runserver
```

**Comment by peritus** [comment]
Still like the rename because we have a proper python module that can be installed (and even if only within a virtual env for tox testing).

**Comment by peritus** [comment]
Mergety-merge-merge ?

**Comment by readevalprint** [comment]
+1 merge all the things!

**Pull request merged**
