### PR TITLE
Re-add a minimal Dockerfile

### PR DESCRIPTION
**Pull request by peritus**
This makes our docker file working again, mostly based on @readevalprint's earlier work.

### CODE REVIEW

**Comment by readevalprint** [comment]
How does this handle uploaded files?

**Comment by peritus** [comment]
Uploaded files ?

**Comment by peritus** [comment]
At this point the django app of gather2 should be completely stateless, i. e. all state is saved in the postgres database.

**Comment by readevalprint** [comment]
Eventually surveys will need to store uploaded files...

**Comment by peritus** [comment]
Noted.

**Pull request merged**
